apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: remove-secret-read-role
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['rbac.authorization.k8s.io']
        apiVersions: ['v1']
        resources: ['roles', 'clusterroles']
        operations: ['CREATE', 'UPDATE']
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "replace",
              path: "/rules",
              value: object.rules.filter(rule, !(rule.resources.exists(r, r == "secrets")))
            }
          ]